#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="restoran")]
	public partial class DataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSlide(Slide instance);
    partial void UpdateSlide(Slide instance);
    partial void DeleteSlide(Slide instance);
    partial void InsertAbout1(About1 instance);
    partial void UpdateAbout1(About1 instance);
    partial void DeleteAbout1(About1 instance);
    partial void InsertTeam(Team instance);
    partial void UpdateTeam(Team instance);
    partial void DeleteTeam(Team instance);
    partial void InsertXidmet(Xidmet instance);
    partial void UpdateXidmet(Xidmet instance);
    partial void DeleteXidmet(Xidmet instance);
    partial void InsertContact(Contact instance);
    partial void UpdateContact(Contact instance);
    partial void DeleteContact(Contact instance);
    partial void InsertCategory(Category instance);
    partial void UpdateCategory(Category instance);
    partial void DeleteCategory(Category instance);
    partial void InsertGender(Gender instance);
    partial void UpdateGender(Gender instance);
    partial void DeleteGender(Gender instance);
    partial void InsertBasket(Basket instance);
    partial void UpdateBasket(Basket instance);
    partial void DeleteBasket(Basket instance);
    partial void InsertMenyu(Menyu instance);
    partial void UpdateMenyu(Menyu instance);
    partial void DeleteMenyu(Menyu instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public DataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["restoranConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Slide> Slides
		{
			get
			{
				return this.GetTable<Slide>();
			}
		}
		
		public System.Data.Linq.Table<About1> About1s
		{
			get
			{
				return this.GetTable<About1>();
			}
		}
		
		public System.Data.Linq.Table<Team> Teams
		{
			get
			{
				return this.GetTable<Team>();
			}
		}
		
		public System.Data.Linq.Table<Xidmet> Xidmets
		{
			get
			{
				return this.GetTable<Xidmet>();
			}
		}
		
		public System.Data.Linq.Table<Contact> Contacts
		{
			get
			{
				return this.GetTable<Contact>();
			}
		}
		
		public System.Data.Linq.Table<Category> Categories
		{
			get
			{
				return this.GetTable<Category>();
			}
		}
		
		public System.Data.Linq.Table<Gender> Genders
		{
			get
			{
				return this.GetTable<Gender>();
			}
		}
		
		public System.Data.Linq.Table<Basket> Baskets
		{
			get
			{
				return this.GetTable<Basket>();
			}
		}
		
		public System.Data.Linq.Table<Menyu> Menyus
		{
			get
			{
				return this.GetTable<Menyu>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<TotalPrice> TotalPrices
		{
			get
			{
				return this.GetTable<TotalPrice>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Slide")]
	public partial class Slide : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SlideId;
		
		private string _SlideName;
		
		private string _SlidePhoto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSlideIdChanging(int value);
    partial void OnSlideIdChanged();
    partial void OnSlideNameChanging(string value);
    partial void OnSlideNameChanged();
    partial void OnSlidePhotoChanging(string value);
    partial void OnSlidePhotoChanged();
    #endregion
		
		public Slide()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SlideId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SlideId
		{
			get
			{
				return this._SlideId;
			}
			set
			{
				if ((this._SlideId != value))
				{
					this.OnSlideIdChanging(value);
					this.SendPropertyChanging();
					this._SlideId = value;
					this.SendPropertyChanged("SlideId");
					this.OnSlideIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SlideName", DbType="NVarChar(50)")]
		public string SlideName
		{
			get
			{
				return this._SlideName;
			}
			set
			{
				if ((this._SlideName != value))
				{
					this.OnSlideNameChanging(value);
					this.SendPropertyChanging();
					this._SlideName = value;
					this.SendPropertyChanged("SlideName");
					this.OnSlideNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SlidePhoto", DbType="NVarChar(MAX)")]
		public string SlidePhoto
		{
			get
			{
				return this._SlidePhoto;
			}
			set
			{
				if ((this._SlidePhoto != value))
				{
					this.OnSlidePhotoChanging(value);
					this.SendPropertyChanging();
					this._SlidePhoto = value;
					this.SendPropertyChanged("SlidePhoto");
					this.OnSlidePhotoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.About1")]
	public partial class About1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AboutId;
		
		private string _AboutText;
		
		private string _AboutPhoto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAboutIdChanging(int value);
    partial void OnAboutIdChanged();
    partial void OnAboutTextChanging(string value);
    partial void OnAboutTextChanged();
    partial void OnAboutPhotoChanging(string value);
    partial void OnAboutPhotoChanged();
    #endregion
		
		public About1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AboutId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AboutId
		{
			get
			{
				return this._AboutId;
			}
			set
			{
				if ((this._AboutId != value))
				{
					this.OnAboutIdChanging(value);
					this.SendPropertyChanging();
					this._AboutId = value;
					this.SendPropertyChanged("AboutId");
					this.OnAboutIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AboutText", DbType="NVarChar(MAX)")]
		public string AboutText
		{
			get
			{
				return this._AboutText;
			}
			set
			{
				if ((this._AboutText != value))
				{
					this.OnAboutTextChanging(value);
					this.SendPropertyChanging();
					this._AboutText = value;
					this.SendPropertyChanged("AboutText");
					this.OnAboutTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AboutPhoto", DbType="NVarChar(MAX)")]
		public string AboutPhoto
		{
			get
			{
				return this._AboutPhoto;
			}
			set
			{
				if ((this._AboutPhoto != value))
				{
					this.OnAboutPhotoChanging(value);
					this.SendPropertyChanging();
					this._AboutPhoto = value;
					this.SendPropertyChanged("AboutPhoto");
					this.OnAboutPhotoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Team")]
	public partial class Team : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TeamId;
		
		private string _TeamName;
		
		private string _TeamVezife;
		
		private string _TeamPhoto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTeamIdChanging(int value);
    partial void OnTeamIdChanged();
    partial void OnTeamNameChanging(string value);
    partial void OnTeamNameChanged();
    partial void OnTeamVezifeChanging(string value);
    partial void OnTeamVezifeChanged();
    partial void OnTeamPhotoChanging(string value);
    partial void OnTeamPhotoChanged();
    #endregion
		
		public Team()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TeamId
		{
			get
			{
				return this._TeamId;
			}
			set
			{
				if ((this._TeamId != value))
				{
					this.OnTeamIdChanging(value);
					this.SendPropertyChanging();
					this._TeamId = value;
					this.SendPropertyChanged("TeamId");
					this.OnTeamIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamName", DbType="NVarChar(50)")]
		public string TeamName
		{
			get
			{
				return this._TeamName;
			}
			set
			{
				if ((this._TeamName != value))
				{
					this.OnTeamNameChanging(value);
					this.SendPropertyChanging();
					this._TeamName = value;
					this.SendPropertyChanged("TeamName");
					this.OnTeamNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamVezife", DbType="NVarChar(50)")]
		public string TeamVezife
		{
			get
			{
				return this._TeamVezife;
			}
			set
			{
				if ((this._TeamVezife != value))
				{
					this.OnTeamVezifeChanging(value);
					this.SendPropertyChanging();
					this._TeamVezife = value;
					this.SendPropertyChanged("TeamVezife");
					this.OnTeamVezifeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamPhoto", DbType="NVarChar(MAX)")]
		public string TeamPhoto
		{
			get
			{
				return this._TeamPhoto;
			}
			set
			{
				if ((this._TeamPhoto != value))
				{
					this.OnTeamPhotoChanging(value);
					this.SendPropertyChanging();
					this._TeamPhoto = value;
					this.SendPropertyChanged("TeamPhoto");
					this.OnTeamPhotoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Xidmet")]
	public partial class Xidmet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _XidmetId;
		
		private string _XidmetName;
		
		private string _XidmetText;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnXidmetIdChanging(int value);
    partial void OnXidmetIdChanged();
    partial void OnXidmetNameChanging(string value);
    partial void OnXidmetNameChanged();
    partial void OnXidmetTextChanging(string value);
    partial void OnXidmetTextChanged();
    #endregion
		
		public Xidmet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XidmetId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int XidmetId
		{
			get
			{
				return this._XidmetId;
			}
			set
			{
				if ((this._XidmetId != value))
				{
					this.OnXidmetIdChanging(value);
					this.SendPropertyChanging();
					this._XidmetId = value;
					this.SendPropertyChanged("XidmetId");
					this.OnXidmetIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XidmetName", DbType="NVarChar(70)")]
		public string XidmetName
		{
			get
			{
				return this._XidmetName;
			}
			set
			{
				if ((this._XidmetName != value))
				{
					this.OnXidmetNameChanging(value);
					this.SendPropertyChanging();
					this._XidmetName = value;
					this.SendPropertyChanged("XidmetName");
					this.OnXidmetNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XidmetText", DbType="NVarChar(MAX)")]
		public string XidmetText
		{
			get
			{
				return this._XidmetText;
			}
			set
			{
				if ((this._XidmetText != value))
				{
					this.OnXidmetTextChanging(value);
					this.SendPropertyChanging();
					this._XidmetText = value;
					this.SendPropertyChanged("XidmetText");
					this.OnXidmetTextChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contact")]
	public partial class Contact : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ContactId;
		
		private string _ContactName;
		
		private string _ContactEmail;
		
		private string _ContactText;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnContactIdChanging(int value);
    partial void OnContactIdChanged();
    partial void OnContactNameChanging(string value);
    partial void OnContactNameChanged();
    partial void OnContactEmailChanging(string value);
    partial void OnContactEmailChanged();
    partial void OnContactTextChanging(string value);
    partial void OnContactTextChanged();
    #endregion
		
		public Contact()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ContactId
		{
			get
			{
				return this._ContactId;
			}
			set
			{
				if ((this._ContactId != value))
				{
					this.OnContactIdChanging(value);
					this.SendPropertyChanging();
					this._ContactId = value;
					this.SendPropertyChanged("ContactId");
					this.OnContactIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactName", DbType="NVarChar(50)")]
		public string ContactName
		{
			get
			{
				return this._ContactName;
			}
			set
			{
				if ((this._ContactName != value))
				{
					this.OnContactNameChanging(value);
					this.SendPropertyChanging();
					this._ContactName = value;
					this.SendPropertyChanged("ContactName");
					this.OnContactNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactEmail", DbType="NVarChar(70)")]
		public string ContactEmail
		{
			get
			{
				return this._ContactEmail;
			}
			set
			{
				if ((this._ContactEmail != value))
				{
					this.OnContactEmailChanging(value);
					this.SendPropertyChanging();
					this._ContactEmail = value;
					this.SendPropertyChanged("ContactEmail");
					this.OnContactEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactText", DbType="NVarChar(MAX)")]
		public string ContactText
		{
			get
			{
				return this._ContactText;
			}
			set
			{
				if ((this._ContactText != value))
				{
					this.OnContactTextChanging(value);
					this.SendPropertyChanging();
					this._ContactText = value;
					this.SendPropertyChanged("ContactText");
					this.OnContactTextChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Category")]
	public partial class Category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CategoryId;
		
		private string _CategoryName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategoryIdChanging(int value);
    partial void OnCategoryIdChanged();
    partial void OnCategoryNameChanging(string value);
    partial void OnCategoryNameChanged();
    #endregion
		
		public Category()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				if ((this._CategoryId != value))
				{
					this.OnCategoryIdChanging(value);
					this.SendPropertyChanging();
					this._CategoryId = value;
					this.SendPropertyChanged("CategoryId");
					this.OnCategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="NVarChar(30)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this.OnCategoryNameChanging(value);
					this.SendPropertyChanging();
					this._CategoryName = value;
					this.SendPropertyChanged("CategoryName");
					this.OnCategoryNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gender")]
	public partial class Gender : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GenderId;
		
		private string _GenderName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGenderIdChanging(int value);
    partial void OnGenderIdChanged();
    partial void OnGenderNameChanging(string value);
    partial void OnGenderNameChanged();
    #endregion
		
		public Gender()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenderId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GenderId
		{
			get
			{
				return this._GenderId;
			}
			set
			{
				if ((this._GenderId != value))
				{
					this.OnGenderIdChanging(value);
					this.SendPropertyChanging();
					this._GenderId = value;
					this.SendPropertyChanged("GenderId");
					this.OnGenderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenderName", DbType="NVarChar(20)")]
		public string GenderName
		{
			get
			{
				return this._GenderName;
			}
			set
			{
				if ((this._GenderName != value))
				{
					this.OnGenderNameChanging(value);
					this.SendPropertyChanging();
					this._GenderName = value;
					this.SendPropertyChanged("GenderName");
					this.OnGenderNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Basket")]
	public partial class Basket : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BasketId;
		
		private string _BasketName;
		
		private System.Nullable<int> _BasketPrice;
		
		private System.Nullable<int> _BasketNumber;
		
		private string _BasketPhoto;
		
		private System.Nullable<int> _BasketUserId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBasketIdChanging(int value);
    partial void OnBasketIdChanged();
    partial void OnBasketNameChanging(string value);
    partial void OnBasketNameChanged();
    partial void OnBasketPriceChanging(System.Nullable<int> value);
    partial void OnBasketPriceChanged();
    partial void OnBasketNumberChanging(System.Nullable<int> value);
    partial void OnBasketNumberChanged();
    partial void OnBasketPhotoChanging(string value);
    partial void OnBasketPhotoChanged();
    partial void OnBasketUserIdChanging(System.Nullable<int> value);
    partial void OnBasketUserIdChanged();
    #endregion
		
		public Basket()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasketId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BasketId
		{
			get
			{
				return this._BasketId;
			}
			set
			{
				if ((this._BasketId != value))
				{
					this.OnBasketIdChanging(value);
					this.SendPropertyChanging();
					this._BasketId = value;
					this.SendPropertyChanged("BasketId");
					this.OnBasketIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasketName", DbType="NVarChar(70)")]
		public string BasketName
		{
			get
			{
				return this._BasketName;
			}
			set
			{
				if ((this._BasketName != value))
				{
					this.OnBasketNameChanging(value);
					this.SendPropertyChanging();
					this._BasketName = value;
					this.SendPropertyChanged("BasketName");
					this.OnBasketNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasketPrice", DbType="Int")]
		public System.Nullable<int> BasketPrice
		{
			get
			{
				return this._BasketPrice;
			}
			set
			{
				if ((this._BasketPrice != value))
				{
					this.OnBasketPriceChanging(value);
					this.SendPropertyChanging();
					this._BasketPrice = value;
					this.SendPropertyChanged("BasketPrice");
					this.OnBasketPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasketNumber", DbType="Int")]
		public System.Nullable<int> BasketNumber
		{
			get
			{
				return this._BasketNumber;
			}
			set
			{
				if ((this._BasketNumber != value))
				{
					this.OnBasketNumberChanging(value);
					this.SendPropertyChanging();
					this._BasketNumber = value;
					this.SendPropertyChanged("BasketNumber");
					this.OnBasketNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasketPhoto", DbType="NVarChar(MAX)")]
		public string BasketPhoto
		{
			get
			{
				return this._BasketPhoto;
			}
			set
			{
				if ((this._BasketPhoto != value))
				{
					this.OnBasketPhotoChanging(value);
					this.SendPropertyChanging();
					this._BasketPhoto = value;
					this.SendPropertyChanged("BasketPhoto");
					this.OnBasketPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasketUserId", DbType="Int")]
		public System.Nullable<int> BasketUserId
		{
			get
			{
				return this._BasketUserId;
			}
			set
			{
				if ((this._BasketUserId != value))
				{
					this.OnBasketUserIdChanging(value);
					this.SendPropertyChanging();
					this._BasketUserId = value;
					this.SendPropertyChanged("BasketUserId");
					this.OnBasketUserIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Menyu")]
	public partial class Menyu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MenyuId;
		
		private string _MenyuName;
		
		private string _MenyuText;
		
		private string _MenyuPhoto;
		
		private System.Nullable<int> _MenyuCategoryId;
		
		private string _MenyuQiymet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMenyuIdChanging(int value);
    partial void OnMenyuIdChanged();
    partial void OnMenyuNameChanging(string value);
    partial void OnMenyuNameChanged();
    partial void OnMenyuTextChanging(string value);
    partial void OnMenyuTextChanged();
    partial void OnMenyuPhotoChanging(string value);
    partial void OnMenyuPhotoChanged();
    partial void OnMenyuCategoryIdChanging(System.Nullable<int> value);
    partial void OnMenyuCategoryIdChanged();
    partial void OnMenyuQiymetChanging(string value);
    partial void OnMenyuQiymetChanged();
    #endregion
		
		public Menyu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenyuId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MenyuId
		{
			get
			{
				return this._MenyuId;
			}
			set
			{
				if ((this._MenyuId != value))
				{
					this.OnMenyuIdChanging(value);
					this.SendPropertyChanging();
					this._MenyuId = value;
					this.SendPropertyChanged("MenyuId");
					this.OnMenyuIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenyuName", DbType="NVarChar(50)")]
		public string MenyuName
		{
			get
			{
				return this._MenyuName;
			}
			set
			{
				if ((this._MenyuName != value))
				{
					this.OnMenyuNameChanging(value);
					this.SendPropertyChanging();
					this._MenyuName = value;
					this.SendPropertyChanged("MenyuName");
					this.OnMenyuNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenyuText", DbType="NVarChar(MAX)")]
		public string MenyuText
		{
			get
			{
				return this._MenyuText;
			}
			set
			{
				if ((this._MenyuText != value))
				{
					this.OnMenyuTextChanging(value);
					this.SendPropertyChanging();
					this._MenyuText = value;
					this.SendPropertyChanged("MenyuText");
					this.OnMenyuTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenyuPhoto", DbType="NVarChar(MAX)")]
		public string MenyuPhoto
		{
			get
			{
				return this._MenyuPhoto;
			}
			set
			{
				if ((this._MenyuPhoto != value))
				{
					this.OnMenyuPhotoChanging(value);
					this.SendPropertyChanging();
					this._MenyuPhoto = value;
					this.SendPropertyChanged("MenyuPhoto");
					this.OnMenyuPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenyuCategoryId", DbType="Int")]
		public System.Nullable<int> MenyuCategoryId
		{
			get
			{
				return this._MenyuCategoryId;
			}
			set
			{
				if ((this._MenyuCategoryId != value))
				{
					this.OnMenyuCategoryIdChanging(value);
					this.SendPropertyChanging();
					this._MenyuCategoryId = value;
					this.SendPropertyChanged("MenyuCategoryId");
					this.OnMenyuCategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenyuQiymet", DbType="NVarChar(10)")]
		public string MenyuQiymet
		{
			get
			{
				return this._MenyuQiymet;
			}
			set
			{
				if ((this._MenyuQiymet != value))
				{
					this.OnMenyuQiymetChanging(value);
					this.SendPropertyChanging();
					this._MenyuQiymet = value;
					this.SendPropertyChanged("MenyuQiymet");
					this.OnMenyuQiymetChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserId;
		
		private string _UserName;
		
		private string _UserPassword;
		
		private string _UserEmail;
		
		private System.Nullable<int> _UserRandomCode;
		
		private System.Nullable<System.DateTime> _UserRandomCodeDate;
		
		private string _UserNumber;
		
		private string _UserPhoto;
		
		private System.Nullable<int> _UserCinsId;
		
		private System.Nullable<System.DateTime> _UserQeydiyyat;
		
		private System.Nullable<int> _UserBalans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnUserPasswordChanging(string value);
    partial void OnUserPasswordChanged();
    partial void OnUserEmailChanging(string value);
    partial void OnUserEmailChanged();
    partial void OnUserRandomCodeChanging(System.Nullable<int> value);
    partial void OnUserRandomCodeChanged();
    partial void OnUserRandomCodeDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUserRandomCodeDateChanged();
    partial void OnUserNumberChanging(string value);
    partial void OnUserNumberChanged();
    partial void OnUserPhotoChanging(string value);
    partial void OnUserPhotoChanged();
    partial void OnUserCinsIdChanging(System.Nullable<int> value);
    partial void OnUserCinsIdChanged();
    partial void OnUserQeydiyyatChanging(System.Nullable<System.DateTime> value);
    partial void OnUserQeydiyyatChanged();
    partial void OnUserBalansChanging(System.Nullable<int> value);
    partial void OnUserBalansChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPassword", DbType="NVarChar(50)")]
		public string UserPassword
		{
			get
			{
				return this._UserPassword;
			}
			set
			{
				if ((this._UserPassword != value))
				{
					this.OnUserPasswordChanging(value);
					this.SendPropertyChanging();
					this._UserPassword = value;
					this.SendPropertyChanged("UserPassword");
					this.OnUserPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserEmail", DbType="NVarChar(50)")]
		public string UserEmail
		{
			get
			{
				return this._UserEmail;
			}
			set
			{
				if ((this._UserEmail != value))
				{
					this.OnUserEmailChanging(value);
					this.SendPropertyChanging();
					this._UserEmail = value;
					this.SendPropertyChanged("UserEmail");
					this.OnUserEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserRandomCode", DbType="Int")]
		public System.Nullable<int> UserRandomCode
		{
			get
			{
				return this._UserRandomCode;
			}
			set
			{
				if ((this._UserRandomCode != value))
				{
					this.OnUserRandomCodeChanging(value);
					this.SendPropertyChanging();
					this._UserRandomCode = value;
					this.SendPropertyChanged("UserRandomCode");
					this.OnUserRandomCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserRandomCodeDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UserRandomCodeDate
		{
			get
			{
				return this._UserRandomCodeDate;
			}
			set
			{
				if ((this._UserRandomCodeDate != value))
				{
					this.OnUserRandomCodeDateChanging(value);
					this.SendPropertyChanging();
					this._UserRandomCodeDate = value;
					this.SendPropertyChanged("UserRandomCodeDate");
					this.OnUserRandomCodeDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNumber", DbType="NVarChar(50)")]
		public string UserNumber
		{
			get
			{
				return this._UserNumber;
			}
			set
			{
				if ((this._UserNumber != value))
				{
					this.OnUserNumberChanging(value);
					this.SendPropertyChanging();
					this._UserNumber = value;
					this.SendPropertyChanged("UserNumber");
					this.OnUserNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPhoto", DbType="NVarChar(70)")]
		public string UserPhoto
		{
			get
			{
				return this._UserPhoto;
			}
			set
			{
				if ((this._UserPhoto != value))
				{
					this.OnUserPhotoChanging(value);
					this.SendPropertyChanging();
					this._UserPhoto = value;
					this.SendPropertyChanged("UserPhoto");
					this.OnUserPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCinsId", DbType="Int")]
		public System.Nullable<int> UserCinsId
		{
			get
			{
				return this._UserCinsId;
			}
			set
			{
				if ((this._UserCinsId != value))
				{
					this.OnUserCinsIdChanging(value);
					this.SendPropertyChanging();
					this._UserCinsId = value;
					this.SendPropertyChanged("UserCinsId");
					this.OnUserCinsIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserQeydiyyat", DbType="DateTime")]
		public System.Nullable<System.DateTime> UserQeydiyyat
		{
			get
			{
				return this._UserQeydiyyat;
			}
			set
			{
				if ((this._UserQeydiyyat != value))
				{
					this.OnUserQeydiyyatChanging(value);
					this.SendPropertyChanging();
					this._UserQeydiyyat = value;
					this.SendPropertyChanged("UserQeydiyyat");
					this.OnUserQeydiyyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserBalans", DbType="Int")]
		public System.Nullable<int> UserBalans
		{
			get
			{
				return this._UserBalans;
			}
			set
			{
				if ((this._UserBalans != value))
				{
					this.OnUserBalansChanging(value);
					this.SendPropertyChanging();
					this._UserBalans = value;
					this.SendPropertyChanged("UserBalans");
					this.OnUserBalansChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TotalPrice")]
	public partial class TotalPrice
	{
		
		private System.Nullable<int> _BasketUserId;
		
		private int _BasketId;
		
		private System.Nullable<int> _Price;
		
		public TotalPrice()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasketUserId", DbType="Int")]
		public System.Nullable<int> BasketUserId
		{
			get
			{
				return this._BasketUserId;
			}
			set
			{
				if ((this._BasketUserId != value))
				{
					this._BasketUserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasketId", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int BasketId
		{
			get
			{
				return this._BasketId;
			}
			set
			{
				if ((this._BasketId != value))
				{
					this._BasketId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int")]
		public System.Nullable<int> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
